### PR TITLE
Include motor and autosave in test application

### PR DESCRIPTION
**Pull request by waynelewis**
Add databases and IOC startup script commands.
Minor updates to build-testapp script to handle pre-existing root directory and to set permissions on the testapp IOC directory.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
The travis static test build is failing due because the linking order is reversed.  `-lmotorSim` must precede `-lmotor`, so `motor` must be after, or below, `motorSim` in `$(everything_LIBS)`.  Otherwise looks fine.

```
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o): In function `motorAxisSetCallback':
/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:256: undefined reference to `motorParam'
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o): In function `motorAxisMove':
/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:463: undefined reference to `motorParam'
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o): In function `motorAxisReportAxis':
/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:151: undefined reference to `motorParam'
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o): In function `motorAxisGetInteger':
/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:231: undefined reference to `motorParam'
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o): In function `motorAxisGetDouble':
/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:246: undefined reference to `motorParam'
/home/travis/build/mdavidsaver/build-epics/root/epics-x86_64-20190221/motor/lib/linux-x86_64/libmotorSimSupport.a(drvMotorSim.o):/home/travis/build/mdavidsaver/build-epics/motor/motorApp/MotorSimSrc/O.linux-x86_64/../drvMotorSim.c:351: more undefined references to `motorParam' follow
```

**Comment by waynelewis** [comment]
Ignore this PR and I will create a new one. I presume it should merge into devel, not master.

**Comment by mdavidsaver** [comment]
Don't bother, I'm on it.

**Comment by waynelewis** [comment]
OK. I'll leave it with you. I presume you can reopen this PR if necessary.

**Pull request closed without merging**
